# Generated by Django 4.0.2 on 2022-10-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='feed',
            field=models.TextField(max_length=50),
        ),
    ]
